# See: http://code.google.com/p/elaunira/downloads/detail?name=lubm-queries-sparql.txt

# query 4
SELECT ?x ?y1 ?y2 ?y3 WHERE {
	?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#Professor> . 
	?x <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#worksFor> <http://www.Department0.University0.edu> . 
	?x <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#name> ?y1 . 
	?x <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#emailAddress> ?y2 .
	?x <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#telephone> ?y3
}
